IMAGE_EXTENSIONS = ".(?:gif|jpg|jpeg|tiff|png|GIF|JPG|JPEG|TIFF|PNG)"
YAML_EXTENSIONS = ".(?:yaml|yml)"
PY_EXTENSIONS = ".(?:py)"
BITBUCKET_NAME="^(tb|ph|tc)([-a-z][a-z-]+)(resources|resource-type|blueprint|toolkit|rgp)$"
SCREENSHOT_PATH = "/Users/haitran/Desktop/temp/screenshot"
PYTHON_PATH = "/Users/haitran/Desktop/temp/code/python"
YAML_PATH = "/Users/haitran/Desktop/temp/code/yaml"
DEFAULT = "/Users/haitran/Desktop/temp/other"
IGNORE_FILE = [".DS_STORE"]